print('Что получится, если скрестить снеговика с вампиром?')
raw_input()
print('обморожение!')
print()
print('Что дантисты называют \'черной дырой\'?')
raw_input()
print('Кариес!')
print()
print('Тук-тук')
raw_input()
print("Кто там?")
raw_input()
print('Невежливая корова.')
raw_input()
print('Невежливая корова?', end='')
raw_input('-МУУУ!')